spring:
  datasource:
    url: jdbc:mariadb://${DB_DESENV_SERVER:oracle.fiap.com.br}:${DB_DESENV_PORT:1521}/${DB_DESENV_NAME:spring-pj-cp-2}?createDatabaseIfNotExist=true
    username: ${DB_DESENV_USERNAME:rm550813}
    password: ${DB_DESENV_PASSWORD:261104}
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
